### ISSUE TITLE
Change API URL endpoint

### ISSUE THREAD

**Issue by lucalbert** [routmoute/routmoute-sirene-bundle#2]
Hello,

The Sirene API URL [has been changed](https://api.insee.fr/catalogue/site/themes/wso2/subthemes/insee/pages/item-info.jag?name=Sirene&version=V3.11&provider=insee).
It is now https://api.insee.fr/entreprises/sirene/V3.11 (to be modified in https://github.com/routmoute/routmoute-sirene-bundle/blob/main/src/Service/RoutmouteSireneApiService .php#L24)

Thanks you

**Comment by routmoute** [comment]
Can you make a PR ?
Thank you
